In [10]:
# Pre Req Imports
import pandas as pd
import io

# Define Excel Sheets

In [ ]:
# Crime
xlsx = pd.ExcelFile("Data_Tables_LGA_Recorded_Offences_Year_Ending_December_2022.xlsx")
Crime_By_Police_Region_Pop = pd.read_excel(xlsx, "Table 01") # Offences recorded and rate per 100,000 population by police region and local government area - January 2013 to December 2022
Crime_By_Offence_Type_Pop = pd.read_excel(xlsx, "Table 02") # Offences recorded and rate per 100,000 population by offence type, local government area and police service area - January 2013 to December 2022
Crime_By_Offence_Type = pd.read_excel(xlsx, "Table 03") # Offences recorded by offence type, local government area and postcode or suburb/town - January 2013 to December 2022
Crime_By_Location_Area = pd.read_excel(xlsx, "Table 04") # Offences recorded by location type and local government area - January 2013 to December 2022
Crime_By_Investigation_Status = pd.read_excel(xlsx, "Table 05") # Offences recorded by investigation status and local government area - January 2013 to December 2022
Crime_By_Drugs = pd.read_excel(xlsx, "Table 06") # Select drug offences by drug type and local government area - January 2013 to December 2022

In [ ]:
# Property
xls = pd.ExcelFile("CleanSuburb_HouseV2021A.xls")
Property_Data = pd.read_excel(xls)

In [11]:
Property_Data

,locality,Median 2011,Median 2012,Median 2013,Median 2014,Median 2015,Median 2016,Median 2017,Median 2018,Median 2019,Median 2020,Median 2021,Median 2022,Change 2020-2021,Change 2011-2021,Growth PA
0,ABBOTSFORD,730000,714000,792500,862500,925000,1187500,1280000,1192500,1050000,1200000,1375000,1517500.0,15.0,88.0,6.5
1,ABERFELDIE,994000,852500,947500,1045000,1207500,1300000,1471000,1498500,1390000,1520000,1880500,1575000.0,24.0,89.0,6.6
2,AINTREE,-,-,-,-,600000,600000,571000,557500,575000,640000,719000,760000.0,12.0,NaN,NaN
3,AIREYS INLET,680000,634000,664000,625500,680000,715000,737500,869000,985000,1132500,1775000,1750000.0,57.0,161.0,10.1
4,AIRPORT WEST,557500,495000,532000,575000,635000,742000,845000,845000,795000,812500,960000,919500.0,18.0,72.0,5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,YARRAM,195500,215000,190000,202500,245000,230000,225000,218000,240000,260000,360000,452500.0,38.0,84.0,6.3
816,YARRAVILLE,607000,613000,696000,710000,810000,900500,1000000,1045000,971000,1030000,1185000,1350000.0,15.0,95.0,6.9
817,YARRAWONGA,270000,300000,302500,297000,300500,320000,324500,345000,375000,456500,560000,695000.0,23.0,107.0,7.6
818,YEA,270000,255000,260000,255000,260000,305000,385000,390000,435500,422500,560000,610000.0,33.0,107.0,7.6
819,YINNAR,208000,221500,220000,240000,182500,230000,270000,245000,255000,292500,460000,562500.0,57.0,121.0,8.3